### PR TITLE
[21265] wrong background color in filter of cost reports

### PR DESCRIPTION
**Pull request by HDinger**
Changed the hover color of the filter items. It is now identical to the hover color of the top menu.

https://community.openproject.org/work_packages/21265

### CODE REVIEW

**Comment by HDinger** [comment]
@NobodysNightmare can you please have a look at his?

**Comment by NobodysNightmare** [comment]
Is there no chance to take the `$primary-color-dark` from our sass files?

Because thinking about other themes (e.g. the magenta ones), this will still look rather bad.

**Comment by NobodysNightmare** [comment]
Also: Isn't the expected color the `$primary-color`? That would be `#3493B3`.

**Comment by NobodysNightmare** [comment]
sad we are not able to use our sas variables... but this will have to do for the time being...

**Pull request merged**
