### PR TITLE
Fix change cost query unit

### PR DESCRIPTION
**Pull request by Azure7111**
This PR should make sure that existing queries can change their cost unit types and be safely stored afterwards.

https://community.openproject.org/work_packages/17166

### CODE REVIEW

**Comment by Azure7111** [comment]
Note that this PR works only in conjunction with https://github.com/finnlabs/openproject-reporting/pull/56 and they should therefore only be merged together.

**Comment by Azure7111** [comment]
Need to add specs

**Comment by Azure7111** [comment]
Please note that the specs can be found in the referenced PR.

**Comment by NobodysNightmare** [comment]
Now the groupings (edit: and other filters set above) are not saved anymore when updating.

I suspect that `prepare_query` restored that before.
I'd still prefer if the code could read `@query.save` and you do not need to reintroduce `prepare_query`, but I am not sure how that will be possible.

**Comment by Azure7111** [comment]
Since all the filters are stored as/within a double linked list its impractical to directly update them in-place, especially since the amount of filters can vary and some order is also relevant. Therefore the easiest solutions seems to be to just store the new filter and abandon the old one altogether, similar to how it was done before.

There may be a way to improve upon this solution by trying to make the `unit` parameter behave like the others. But this seems to entail some more changes as I saw multiple spots where the special behaviour seems to be expected, this includes some specs. See https://community.openproject.org/work_packages/19902 for that.

Because of this I basically tried to fix the original implementation.

**Pull request merged**
